# Generated by Django 4.2.2 on 2023-06-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('pais', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Kayakista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('ubicacion', models.CharField(max_length=40)),
                ('club', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Travesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kayakista', models.CharField(max_length=40)),
                ('ubicacion', models.CharField(max_length=40)),
                ('distancia', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
