# Generated by Django 4.2.1 on 2023-06-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kayakeando', '0003_rename_descripcion_travesia_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='ciudad',
            new_name='localidad',
        ),
        migrations.AddField(
            model_name='club',
            name='provincia',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='travesia',
            name='distancia',
            field=models.CharField(max_length=40),
        ),
    ]
